// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Header } from "@/components/Header";
// import SiteFooter from "@/components/site-footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}><Header/>{children}<SiteFooter/></body>
//     </html>
//   );
// }



import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { StoreProvider } from "@/context/StoreContext";
import { Header } from "@/components/Header";
import SiteFooter from "@/components/site-footer";
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <StoreProvider><Header/>{children}<SiteFooter/></StoreProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
